# Generated by Django 5.0.3 on 2024-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='translate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
