# Generated by Django 5.0.3 on 2024-03-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_alter_translate_translate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='translate',
            options={'ordering': ['language', 'translation_key']},
        ),
        migrations.AlterModelOptions(
            name='translationkey',
            options={'ordering': ['key']},
        ),
    ]
